class Sample < ActiveRecord::Base
  generator_for :geo_accession => 'GSM1234'
  generator_for :title => 'Sample Title'
  generator_for :organism => 'rat'
  generator_for :sample_type => 'sample_type'
  generator_for :source_name => 'source_name'
  generator_for :characteristics => 'characteristics'
  generator_for :treatment_protocol => 'treatment_protocol'
  generator_for :extract_protocol => 'extract_protocol'
  generator_for :label => 'label'
  generator_for :label_protocol => 'label_protocol'
  generator_for :scan_protocol => 'scan_protocol'
  generator_for :hyp_protocol => 'hyp_protocol'
  generator_for :description => 'description'
  generator_for :data_processing => 'data_processing'
  generator_for :molecule => 'molecule'
end
